//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `Game.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

/* eslint-disable */
/* jshint ignore: start */

(function(module, require, exports)
{
    const Ice = require("ice").Ice;
    const _ModuleRegistry = Ice._ModuleRegistry;
    const Slice = Ice.Slice;

    let Game = _ModuleRegistry.module("Game");

    Game.CellDTO = class
    {
        constructor(isLandMine = false, value = 0, hide = false, showAll = false, isMarked = false)
        {
            this.isLandMine = isLandMine;
            this.value = value;
            this.hide = hide;
            this.showAll = showAll;
            this.isMarked = isMarked;
        }

        _write(ostr)
        {
            ostr.writeBool(this.isLandMine);
            ostr.writeInt(this.value);
            ostr.writeBool(this.hide);
            ostr.writeBool(this.showAll);
            ostr.writeBool(this.isMarked);
        }

        _read(istr)
        {
            this.isLandMine = istr.readBool();
            this.value = istr.readInt();
            this.hide = istr.readBool();
            this.showAll = istr.readBool();
            this.isMarked = istr.readBool();
        }

        static get minWireSize()
        {
            return  8;
        }
    };

    Slice.defineStruct(Game.CellDTO, true, false);

    Slice.defineSequence(Game, "PixelArrayHelper", "Game.CellDTO", true);

    Slice.defineSequence(Game, "PixelMatrixHelper", "Game.PixelArrayHelper", false);

    const iceC_Game_GameServices_ids = [
        "::Game::GameServices",
        "::Ice::Object"
    ];

    Game.GameServices = class extends Ice.Object
    {
    };

    Game.GameServicesPrx = class extends Ice.ObjectPrx
    {
    };

    Slice.defineOperations(Game.GameServices, Game.GameServicesPrx, iceC_Game_GameServices_ids, 0,
    {
        "selectCell": [, , , , [1], [[3], [3]], , , , ],
        "getBoard": [, , , , ["Game.PixelMatrixHelper"], , , , , ],
        "resetGame": [, , , , , , , , , ]
    });

    const iceC_Game_Observer_ids = [
        "::Game::Observer",
        "::Ice::Object"
    ];

    Game.Observer = class extends Ice.Object
    {
    };

    Game.ObserverPrx = class extends Ice.ObjectPrx
    {
    };

    Slice.defineOperations(Game.Observer, Game.ObserverPrx, iceC_Game_Observer_ids, 0,
    {
        "notifyMessage": [, , , , , [[7]], , , , ]
    });

    const iceC_Game_Subject_ids = [
        "::Game::Subject",
        "::Ice::Object"
    ];

    Game.Subject = class extends Ice.Object
    {
    };

    Game.SubjectPrx = class extends Ice.ObjectPrx
    {
    };

    Slice.defineOperations(Game.Subject, Game.SubjectPrx, iceC_Game_Subject_ids, 0,
    {
        "attachObserver": [, , , , , [["Game.ObserverPrx"]], , , , ]
    });
    exports.Game = Game;
}
(typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? module : undefined,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? require :
 (typeof WorkerGlobalScope !== "undefined" && self instanceof WorkerGlobalScope) ? self.Ice._require : window.Ice._require,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? exports :
 (typeof WorkerGlobalScope !== "undefined" && self instanceof WorkerGlobalScope) ? self : window));
